/* Дополнение существующей игры: исследование этажей. */
(function(){
const EX_KEY='chronicles_tower_exploration_v2';
const ROOM_TYPES=[['🕯️','Тёмный коридор','Осмотреть стены и пол.'],['📦','Заброшенная кладовая','Проверить старые сундуки.'],['⛩️','Святилище','Исследовать древний алтарь.'],['🕳️','Трещина Бездны','Заглянуть в холодный разлом.'],['🗝️','Запечатанная дверь','Осмотреть старую печать.'],['👁️','Зал стража','Проверить присутствие врага.']];
let exploration={floor:0,rooms:[],searched:0};
function saveExploration(){try{localStorage.setItem(EX_KEY,JSON.stringify(exploration))}catch(e){}}
function loadExploration(){try{const x=JSON.parse(localStorage.getItem(EX_KEY));if(x&&Array.isArray(x.rooms))exploration=x}catch(e){}}
function prepareFloor(f){if(exploration.floor===f&&exploration.rooms.length)return;exploration={floor:f,searched:0,rooms:ROOM_TYPES.slice().sort(()=>Math.random()-.5).slice(0,5).map((r,i)=>({id:i,title:r[0]+' '+r[1],desc:r[2],done:false}))};saveExploration()}
function explorationScreen(){prepareFloor(state.floor);return `<div class="card"><h2>🗺️ Исследование ${state.floor} этажа</h2><div class="notice">Исследуй комнаты этажа до покорения и получай дополнительные награды.</div><div class="small muted">Исследовано: ${exploration.searched}/${exploration.rooms.length}</div>${exploration.rooms.map((r,i)=>`<button class="choice" ${r.done?'disabled':''} onclick="searchExplorationRoom(${i})"><b>${r.title}${r.done?' ✅':''}</b><br><span class="small muted">${r.done?'Комната уже исследована.':r.desc}</span></button>`).join('')}<button class="btn primary" onclick="finishExploration()">⚔️ Закончить исследование и перейти к бою</button><button class="btn" onclick="go('tower')">↩️ Вернуться к этажу</button></div>`}
function searchExplorationRoom(i){if(state.screen!=='explore')return;const r=exploration.rooms[i];if(!r||r.done||!state.hero)return;r.done=true;exploration.searched++;const f=state.floor,h=state.hero,roll=Math.random();if(roll<.2){const gold=8+Math.floor(Math.random()*18)+f;h.gold+=gold;log('Исследование: найден тайник с '+gold+' 🪙.','good')}else if(roll<.38){const heal=Math.max(8,Math.floor(maxHp()*.12));h.hp=Math.min(maxHp(),h.hp+heal);log('Исследование: найдено лекарство. +'+heal+' HP.','good')}else if(roll<.55){const gained=10+f*2;gainXP(gained);log('Исследование: древняя надпись дала '+gained+' XP.','good')}else if(roll<.7){const dmg=Math.max(1,4+Math.floor(f/3)-def());h.hp=Math.max(1,h.hp-dmg);log('Исследование: ловушка нанесла '+dmg+' урона.','combat')}else if(roll<.86){h.potions++;log('Исследование: найдено зелье.','good')}else log('Исследование: ты чувствуешь наблюдение из темноты.');saveExploration();save();render()}
function finishExploration(){if(state.screen!=='explore')return;state.screen='tower';save();enterFloor()}
window.searchExplorationRoom=searchExplorationRoom;window.finishExploration=finishExploration;loadExploration();
const originalTower=tower;window.tower=function(){const html=originalTower();if(state.floor<=50&&state.hero)return html.replace('onclick="enterFloor()">⬆️ Покорять этаж '+state.floor,'onclick="openExploration()">🗺️ Исследовать этаж '+state.floor+'</button><button class="btn primary" onclick="enterFloor()">⬆️ Покорять этаж '+state.floor);return html};
const originalRender=render;window.render=function(){if(state.screen==='explore'){document.getElementById('app').innerHTML=header()+`<main id="screen">${explorationScreen()}</main>`+'<footer><div class="grid3"><button class="btn" onclick="go(\'tower\')">🏰 Башня</button><button class="btn" onclick="go(\'character\')">👤 Герой</button><button class="btn" onclick="go(\'inventory\')">🎒 Инвентарь</button></div></footer>';return}return originalRender()};
window.openExploration=function(){if(!state.hero||state.floor>50)return;prepareFloor(state.floor);state.screen='explore';save();render()};
})();
